/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as eathasysNftSol from "./EathasysNFT.sol";
export type { eathasysNftSol };
import type * as interfaces from "./Interfaces";
export type { interfaces };
export type { EarthasysERC20 } from "./EarthasysERC20";
export type { Oracle } from "./Oracle";
export type { Protocol } from "./Protocol";
